version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run:
          name: "Flutter Doctor"
          command: "flutter doctor"
      - run:
          name: "Testing"
          command: "flutter test"
      - run:
          name: "Build Android"
          command: "flutter -v build apk"
#      - run: flutter doctor
#      - run: flutter test
#      - run: flutter -v build apk
#      - run: flutter -v build ios
