version: 2.1
orbs:
  flutter: circleci/flutter@1.1.0
jobs:
  android_job:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run:
          name: "Flutter Doctor"
          command: "flutter doctor"
      - run:
          name: "Pub Get"
          command: "flutter pub get"
      - run:
          name: "Flutter build Android"
          command: "flutter build apk --debug"

  ios_job:
    macos:
      xcode: 13.3.1
    steps:
      - flutter/install_sdk:
          version: "3.0.1"
      - checkout


  flutter_doctor:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter test --coverage

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - ios_job
      - android_job