version: '2.1'
orbs:
  flutter: circleci/flutter@1.0
jobs:
  build:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          version: 2.10.2
      - flutter/install_android_gradle
      - flutter/install_android_gem
      - flutter/install_ios_pod
      - flutter/install_ios_gem 
      - run:
          name: "Flutter Doctor"
          command: "flutter doctor"
      - run:
          name: "Testing"
          command: "flutter test"
      - run:
          name: "Build Android"
          command: "flutter -v build apk"
      - run:
          name: "Build IOS"
          command: "flutter -v build ios"
