version: 2
orbs:
  android: circleci/android@1.0.3
  flutter: circleci/flutter@1.0
jobs:
  android_job:
    executor:
      name: android/android-machine
    steps:
      - flutter/install_sdk_and_pub:
          version: 2.2.3
      - flutter/install_android_gradle
      - flutter/install_android_gem
      - run:
          command: bundle exec fastlane distribute
          working_directory: ios

  ios_job:
    macos:
      xcode: 12.5.1
    steps:
      - flutter/install_sdk_and_pub:
          version: 2.2.3
      - flutter/install_ios_pod
      - flutter/install_ios_gem
      - run:
          command: bundle exec fastlane distribute
          working_directory: ios

  flutter_doctor:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter test --coverage

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - flutter_doctor
      - android_job:
          requires:
            - flutter_doctor
          filters:
            branches:
              only: main
      - ios_job:
          requires:
            - flutter_doctor
          filters:
            branches:
              only: main