version: 2.1
orbs:
  flutter: circleci/flutter@1.1.0
  ruby: circleci/ruby@1.2.0
jobs:
  android_job:
    docker:
      - image: cirrusci/flutter
    working_directory: /Users/distiller/jenkins_test
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: playstore
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: "Install Fastlane"
          command: "gem install fastlane"
      - run:
          name: "Flutter Doctor"
          command: "flutter doctor"
      - run:
          name: "Pub Get"
          command: "flutter pub get"
      - run:
          name: "Flutter build Android"
          command: "flutter build apk --debug"
      - run:
          name: fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  ios_job:
    macos:
      xcode: 13.3.1
    steps:
      - flutter/install_sdk:
          version: "3.0.1"
      - checkout

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - android_job