version: 2.1
orbs:
  android: circleci/android@1.0.3
  flutter: circleci/flutter@1.0
jobs:
  android_job:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run:
          name: "Flutter Doctor"
          command: "flutter doctor"
      - run:
          name: "Pub Get"
          command: "flutter pub get"
      - run:
          name: "Flutter build Android"
          command: "flutter build apk --debug"

  ios_job:
    macos:
      xcode: 12.5.1
    steps:
      - checkout:
          path: ~/flutter-app
      - restore_cache:
          key: bundle-v2-{{ checksum "ios/Gemfile" }}-{{ arch }}
      - run:
          name: Setup environment variables
          command: echo 'export PATH="$PATH:`pwd`/flutter/bin"'  >> $BASH_ENV
      - run:
          name: Download flutter SDK
          command: if ! test -f "flutter_sdk.zip"; then curl -o flutter_sdk.zip https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_v1.9.1+hotfix.4-stable.zip; fi
      - run:
          name: Unzip flutter SDK
          command: unzip flutter_sdk.zip
      - run:
          name: Checking xcode version
          command: xcodebuild -version
      - run:
          name: Set xcode path
          command: sudo xcode-select -s /Applications/Xcode-10.3.app/Contents/Developer
      - run:
          name: Checking xcode path
          command: xcode-select -p
      - run: flutter upgrade
      - run:
          command: flutter pub get

  flutter_doctor:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter test --coverage

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - ios_job