version: 2
jobs:
  android_job:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout

  ios_job:
    macos:
      xcode: 12.5.1
    steps:
      - checkout

  flutter_doctor:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: pub get
      - run: flutter test --coverage

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - android_job:
          requires:
            - flutter_doctor
          filters:
            branches:
              only: main
      - ios_job:
          requires:
            - flutter_doctor
          filters:
            branches:
              only: main