version: 2
jobs:
  android_job:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run:
          name: "Flutter Doctor"
          command: "flutter doctor"
      - run:
          name: "Pub Get"
          command: "flutter pub get"

  ios_job:
    macos:
      xcode: 12.5.1
    working_directory: ~/flutter-app
    steps:
      - checkout
      - run:
          name: "Flutter Doctor"
          command: "flutter doctor"
      - run:
          name: "Pub Get"
          command: "flutter pub get"

  flutter_doctor:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter test --coverage

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - flutter_doctor
      - android_job:
          requires:
            - flutter_doctor
          filters:
            branches:
              only: main
      - ios_job:
          requires:
            - flutter_doctor
          filters:
            branches:
              only: main