version: 2
jobs:
  android_job:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run:
          name: "Flutter Doctor"
          command: "flutter doctor"
      - run:
          name: "Pub Get"
          command: "flutter pub get"

  ios_job:
    macos:
      xcode: 12.5.1
    steps:
      - flutter/install_sdk_and_pub:
          version: 2.2.3
      - flutter/install_ios_pod
      - flutter/install_ios_gem
      - run:
          name: "Flutter Doctor"
          command: "flutter doctor"
      - run:
          name: "Pub Get"
          command: "flutter pub get"

  flutter_doctor:
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter test --coverage

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - flutter_doctor
      - android_job
      - ios_job