version: 2
machine:
  environment:
    ANDROID_HOME: "/usr/local/share/android-sdk"
    ANDROID_SDK_HOME: "/usr/local/share/android-sdk"
    ANDROID_SDK_ROOT: "/usr/local/share/android-sdk"
dependencies:
  override:
    - brew tap caskroom/cask
    - brew tap caskroom/versions
    - brew cask install android-sdk
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run:
          name: "Flutter Doctor"
          command: "flutter doctor"
      - run:
          name: "Testing"
          command: "flutter test"
      - run:
          name: "Build Android"
          command: "flutter -v build apk"
      - run:
          name: "Build IOS"
          command: "flutter -v build ios"