version: '2.1'
orbs:
  flutter: circleci/flutter@1.0
jobs:
  build:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run:
          name: "Flutter Doctor"
          command: "flutter doctor"
      - run:
          name: "Testing"
          command: "flutter test"
      - run:
          name: "Build Android"
          command: "flutter -v build apk"
      - run:
          name: "Build IOS"
          command: "flutter -v build ios"
